export type Book = {
  id: string;
  title: string;
  image: string;
  headline: string;
  tags: string;
  color: BookColor;
  createdAt: string;
};

export const ColorPalette = [
  "gray",
  "red",
  "orange",
  "yellow",
  "lime",
  "green",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "fuchsia",
  "pink",
] as const;

export type BookColor = (typeof ColorPalette)[number];

const BOOK_LIBRARY: Book[] = [
  {
    id: "10x-engineer",
    title: "10x Engineering",
    image: "10x-engineer.jpg",
    headline: "Money, fame, maintainable code",
    color: "fuchsia",
    tags: "development, productivity, quality, engineering, 10x engineer",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "agile-micromanagement",
    title: "Agile Project Micromanagement",
    image: "agile-micromanagement.png",
    headline: 'Cognitive Dissonance as "Process" | Water-Fall with Stand-ups',
    color: "red",
    tags: "agile, management, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "mastering-telegram-bot-integration",
    title: "Mastering Telegram Bot Integration",
    image: "mastering-telegram-bot-integration.jpeg",
    headline:
      "Getting user id from the Telegram API | Ah shit, here we go again",
    color: "blue",
    tags: "telegram, bot, development, programming, startup, user",
    createdAt: "2024-09-19T19:00:00.000Z",
  },
  {
    id: "coding-with-gpt",
    title: "Coding with GPT",
    image: "coding-with-gpt.jpeg",
    headline: "Introducing the uncanny valley into your codebase | 7th Edition",
    color: "blue",
    tags: "development, chatgpt, machine learning",
    createdAt: "2024-10-01T12:00:00.000Z",
  },
  {
    id: "fascism",
    title: "Fascism",
    image: "fascism.jpeg",
    headline: "Eroding democracy, 140 characters at a time",
    color: "red",
    tags: "politics, culture",
    createdAt: "2024-07-06T10:00:00.000Z",
  },
  {
    id: "anchor",
    title: "Anchor",
    image: "anchor.jpg",
    headline: "Eating glass on Solana painlessly",
    color: "violet",
    tags: "Rust, blockchain, cryptocurrency, development",
    createdAt: "2024-02-04T13:00:00.000Z",
  },
  {
    id: "arbitrary-forecasts",
    title: "Arbitrary Forecasts",
    image: "arbitrary-forecasts.jpg",
    headline: "Saying something so people feel better about giving you money",
    color: "indigo",
    tags: "business, finance, predictions, management, startup",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "arduino-led-to-blink",
    title: "Getting an Arduino LED to Blink",
    image: "arduino-led-to-blink.jpg",
    headline:
      "Looks like it's back to pixels for you! | And Then Losing Interest",
    color: "blue",
    tags: "Arduino, electronics, hobby, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "avoid-using-dark-patterns",
    title: "Avoid Using Dark Patterns",
    image: "avoid-using-dark-patterns.jpg",
    headline: "Do. Or do not. There is no try.",
    color: "indigo",
    tags: "code, patterns, design, principles",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "avoiding-data-structures",
    title: "Avoiding Data Structures",
    image: "avoiding-data-structures.jpg",
    headline: "Just use HashMaps! | For Minecraft Modders",
    color: "sky",
    tags: "data, algorithms, development, Minecraft, java, architecture",
    createdAt: "2024-01-27T12:00:00.000Z",
  },
  {
    id: "blaming-architecture",
    title: "Blaming the Architecture",
    image: "blaming-architecture.jpeg",
    headline: "Fundamentals of establishing a scapegoat",
    color: "teal",
    tags: "architecture, software, design, culture, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "blaming-the-user",
    title: "Blaming the User",
    image: "blaming-the-user.jpg",
    headline: "You're a 10x hacker and it must be someone else's fault.",
    color: "blue",
    tags: "user, customer, UX, UI, frontend, development, 10x engineer",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "bloated-jabbascript",
    title: "Bloated JabbaScript Frameworks",
    image: "bloated-jabbascript.jpg",
    headline:
      "Han ma boo-kee, keelee ka-lya dooka. Wadja da boolya ra 1.9 Megabytes",
    color: "indigo",
    tags: "JavaScript, frontend, web, html, development, frameworks, performance",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "bracket-placement",
    title: "Bracket Placement",
    image: "bracket-placement.png",
    headline: "From Friend To Enemy In Just One Day",
    color: "teal",
    tags: "style, syntax, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "breaking-back-button",
    title: "Breaking the Back Button",
    image: "breaking-back-button.jpg",
    headline: "Ruining something the browser gave you for free",
    color: "blue",
    tags: "web, user, UX, UI, frontend, browser, development, compatibility, broken",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "breaking-important-stuff-on-friday",
    title: "Breaking important stuff on Friday",
    image: "breaking-important-stuff-on-friday.jpg",
    headline:
      "When the clock hits five, that's your problem now | Just let the intern fix it",
    color: "teal",
    tags: "Friday, deployment, development, risk, devops, broken",
    createdAt: "2024-01-27T12:00:00.000Z",
  },
  {
    id: "broken-dependencies",
    title: "Resolving Broken Dependencies",
    image: "broken-dependencies.jpg",
    headline: "What did I do to deserve this?",
    color: "fuchsia",
    tags: "dependencies, development, debugging, broken",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "building-ai-with-html",
    title: "Building AI with HTML",
    image: "building-ai-with-html.jpg",
    headline: "HyperText Machine Icarning",
    color: "lime",
    tags: "chatgpt, HTML, machine learning, web, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "buzzword-first-design",
    title: "Buzzword-first Design",
    image: "buzzword-first-design.jpg",
    headline: "Fashion-forward development",
    color: "red",
    tags: "design, development, trends, dependencies",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "casual-sexism",
    title: "Casual Sexism",
    image: "casual-sexism.jpg",
    headline:
      "Ensuring half the potential talent force feels uncomfortable and alienated",
    color: "blue",
    tags: "culture, diversity, team, management",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "changing-stuff-and-seeing",
    title: "Changing Stuff and Seeing What Happens",
    image: "changing-stuff-and-seeing.jpg",
    headline: "How to actually learn any new programming concept",
    color: "pink",
    tags: "learning, development, debugging",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "choosing-based-on-github",
    title: "Choosing Based on GitHub Stars",
    image: "choosing-based-on-github.jpg",
    headline: "Depending on a vague popularity contest",
    color: "pink",
    tags: "GitHub, open source, popularity, decision making",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "code-quality",
    title: "Useless Code Quality Metrics",
    image: "code-quality.jpeg",
    headline: "Blindly adhering to arbitrary standards",
    color: "violet",
    tags: "code, quality, metrics, standards, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "coding-drunk",
    title: "Coding Drunk",
    image: "coding-drunk.jpg",
    headline: "Thinking Outside The Bottle | Make Programming Fun Again",
    color: "blue",
    tags: "code, creativity, development, fun",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "coding-on-weekend",
    title: "Coding on the Weekend",
    image: "coding-on-weekend.jpg",
    headline:
      "a frustrating hobby | it's like weekday coding, but pants are optional",
    color: "teal",
    tags: "code, hobby, weekend, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "coffee-into-code",
    title: "Turning Coffee Into Code",
    image: "coffee-into-code.jpg",
    headline:
      "It would be a pure function if not for the side effects on your sanity",
    color: "indigo",
    tags: "coffee, code, development, productivity",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "collective-intelligence",
    title: "Collective Intelligence",
    image: "collective-intelligence.jpg",
    headline: "Building Smart Web 2.0 Applications",
    color: "teal",
    tags: "intelligence, collaboration, team, science",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "compile-and-pray",
    title: "Compile Again and Pray to Work",
    image: "compile-and-pray.jpeg",
    headline: "Because something may change",
    color: "green",
    tags: "development, debugging, error",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "compression",
    title: "JPEG compression",
    image: "compression.jpeg",
    headline: "jpeg",
    color: "blue",
    tags: "JPEG, compression, processing, optimization",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "convoluted-coding-practices",
    title:
      "Using Convoluted Coding Practices to Piece Together a Somehow Functional Product",
    image: "convoluted-coding-practices.jpg",
    headline:
      "Gain expertise using phrases similar to \"If it ain't broke, don't fix it\"",
    color: "red",
    tags: "code, development, complexity",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "cookie-consent",
    title: "Cookie Consent and Other Ways to Obstruct the Web Page",
    image: "cookie-consent.png",
    headline: "Because the Web isn't unusable enough yet",
    color: "blue",
    tags: "web, development, UX, UI, frontend",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "copying-and-pasting",
    title: "Copying and Pasting from Stack Overflow",
    image: "copying-and-pasting.jpg",
    headline: "Cutting corners to meet arbitrary management deadlines",
    color: "teal",
    tags: "Stack Overflow, development, deadlines, chatgpt, copy-pasting",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "copying-snippets-from-pages-made-in-2003",
    title: "Copying snippets from pages made in 2003",
    image: "copying-snippets-from-pages-made-in-2003.jpg",
    headline: "No, no. That's not what I want.",
    color: "red",
    tags: "Stack Overflow, development, copy-pasting",
    createdAt: "2024-01-27T12:00:00.000Z",
  },
  {
    id: "cpp-profiling-on-linux",
    title: "C++ profiling on Linux",
    image: "cpp-profiling-on-linux.jpg",
    headline: "Powered by Rolex | Bring your watch, mate",
    color: "fuchsia",
    tags: "C++, Linux, performance, optimization",
    createdAt: "2024-01-27T12:00:00.000Z",
  },
  {
    id: "cross-browser-code",
    title: "My Code is Cross-Browser Compatible",
    image: "cross-browser-code.png",
    headline:
      "and other lies you tell yourself | designing large-scale web sites",
    color: "teal",
    tags: "browser, UI, UX, frontend, development, compatibility, design",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "ctr-c-ctr-v",
    title: "CTR+C CTR+V",
    image: "ctr-c-ctr-v.jpg",
    headline: "Licensing Guide",
    color: "lime",
    tags: "copy-pasting, google, github, open source",
    createdAt: "2024-01-27T12:00:00.000Z",
  },
  {
    id: "dan-abramov-says",
    title: "Whatever Dan Abramov says to do",
    image: "dan-abramov-says.jpeg",
    headline: "Pure, functional, predictable, time travelling, handsome",
    color: "indigo",
    tags: "Dan Abramov, functional programming, React, JavaScript, tutorial",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "deleting-a-dropped-project",
    title: "Deleting a dropped project",
    image: "deleting-a-dropped-project.jpg",
    headline: "As clients minds change, so does your self esteem",
    color: "fuchsia",
    tags: "project management, development",
    createdAt: "2024-01-27T12:00:00.000Z",
  },
  {
    id: "deleting-code",
    title: "Deleting Code",
    image: "deleting-code.jpg",
    headline:
      "Oh how good it feels | Probably the most satisfying part of your job. Is that sad?",
    color: "teal",
    tags: "code, refactoring, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "demon-extraction",
    title: "Demon Extraction",
    image: "demon-extraction.jpg",
    headline: "A Guide To Removing Unwanted Evil Spirits",
    color: "red",
    tags: "debugging, troubleshooting, software, maintenance",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "destructive-git-commands",
    title: "Destructive Git Commands",
    image: "destructive-git-commands.jpg",
    headline: "WTF just happened? | I hope you backed up your code",
    color: "green",
    tags: "GitHub, commands, mistakes",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "develop-in-prod",
    title: "Developing in Production",
    image: "develop-in-prod.jpeg",
    headline: "The fastest time to market",
    color: "lime",
    tags: "production, development, deployment, risk",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "docker",
    title: "Docker",
    image: "docker.jpg",
    headline: "Docker Docker Docker",
    color: "red",
    tags: "docker, devops, containers, deployment",
    createdAt: "2024-06-06T20:10:00.000Z",
  },
  {
    id: "draft-testing",
    title: "Draft Testing",
    image: "draft-testing.jpg",
    headline: "Just pretend you did it",
    color: "red",
    tags: "testing, development, debugging",
    createdAt: "2024-06-06T20:20:00.000Z",
  },
  {
    id: "drinking-with-ansible",
    title: "Drinking with Ansible",
    image: "drinking-with-ansible.jpg",
    headline: "Running playbook again and again | Drunk from kvas",
    color: "red",
    tags: "automation, devops",
    createdAt: "2024-02-04T13:00:00.000Z",
  },
  {
    id: "drop-table",
    title: "Drop Table",
    image: "drop-table.jpg",
    headline: "Now with user-generated content!",
    color: "teal",
    tags: "SQL, database, user, data, management",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "endless-boilerplate",
    title: "Endless Boilerplate",
    image: "endless-boilerplate.jpg",
    headline: "Hello, ridiculously complicated world",
    color: "cyan",
    tags: "code, complexity, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "estimating-standard-tasks",
    title: "Estimating Standard Tasks",
    image: "estimating-standard-tasks.jpg",
    headline: "How to become the stand-up golden boy",
    color: "red",
    tags: "agile, development, time, meetings",
    createdAt: "2024-06-06T20:30:00.000Z",
  },
  {
    id: "everything-is-a-fscking-dns-problem",
    title: "Everything is a Fscking DNS Problem",
    image: "everything-is-a-fscking-dns-problem.jpg",
    headline: "Editing /etc/hosts for a living",
    color: "blue",
    tags: "DNS, networks, troubleshooting, sysadmin",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "excuses-for-no-documentation",
    title: "Excuses for Now Writing Documentation",
    image: "excuses-for-no-documentation.jpg",
    headline:
      "Where's the fun in just knowing what the code is supposed to do?",
    color: "teal",
    tags: "documentation, development, communication, excuses",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "exiting-vim",
    title: "Exiting Vim",
    image: "exiting-vim.jpg",
    headline:
      "Just memorize these fourteen contextually dependent instructions",
    color: "blue",
    tags: "Vim, text editor, commands, complexity",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "explaining-monads-to-people-who-dont-care",
    title: "Explaining Monads to people who don't care",
    image: "explaining-monads-to-people-who-dont-care.jpg",
    headline:
      "A dogmatic approach to nonexistent problems | Monad is just a monoid in the category of endofunctors. What's the problem?",
    color: "cyan",
    tags: "monads, functional programming, Haskell, category theory, paradigm",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "exploiting-goodwill",
    title: "Exploiting Goodwill to advance your agenda",
    image: "exploiting-goodwill.png",
    headline: "why deny equal opportunity for all to contribute?",
    color: "teal",
    tags: "luck, opportunity, collaboration",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "fake-news-generation",
    title: "Fake news generation",
    image: "fake-news-generation.jpg",
    headline: "Putting NLP to good use",
    color: "violet",
    tags: "NLP, chatgpt, generation, science",
    createdAt: "2024-01-27T13:00:00.000Z",
  },
  {
    id: "farting-in-public",
    title: "Farting in Public",
    image: "farting-in-public.jpg",
    headline: "Public farting explained",
    color: "blue",
    tags: "guide, tutorial, fun, excuses",
    createdAt: "2024-07-06T10:00:00.000Z",
  },
  {
    id: "faster-hardware",
    title: "Throwing Faster Hardware At The Problem",
    image: "faster-hardware.jpg",
    headline:
      "Speeding up your software without needing to actually optimize your code",
    color: "violet",
    tags: "cpu, gpu, ram, memory, hardware, optimization, performance, devops",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "fear-of-missing-out",
    title: "Fear of Missing Out",
    image: "fear-of-missing-out.jpg",
    headline:
      "If you're not running distributed Rust, Go, Elixir and Scala microservices with an elm front end, Apache Storm stream processing, and integrating with Facebook Messenger, Amazon Echo, and gathering machine learning data from my Samsung refrigerator, what are you even doing?",
    color: "indigo",
    tags: "FOMO, technology, trends, microservices",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "fiddling-with-the-padding",
    title: "Fiddling with the Padding",
    image: "fiddling-with-the-padding.jpeg",
    headline:
      "Trying not to think about the economic value of this activity | For hours",
    color: "blue",
    tags: "html, css, UI, UX, design, frontend, style",
    createdAt: "2024-08-11T12:00:00.000Z",
  },
  {
    id: "finding-your-own-stack-overflow-posts",
    title: "Finding Your Own Stack Overflow Posts",
    image: "finding-your-own-stack-overflow-posts.jpg",
    headline: "It's almost like you've had this problem before",
    color: "sky",
    tags: "Stack Overflow, development, debugging, problem-solving",
    createdAt: "2024-01-27T13:00:00.000Z",
  },
  {
    id: "fitting-actual-user-data",
    title: "Fitting Actual User Data Into The Design",
    image: "fitting-actual-user-data.jpg",
    headline: "People have names of varying lengths, who knew?",
    color: "teal",
    tags: "design, user, data, UX, UI, frontend, Javascript, HTML, CSS",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "fizz-buzz",
    title: "Fizz Buzz",
    image: "fizz-buzz.jpeg",
    headline: "Ensuring the futility of your interview process",
    color: "teal",
    tags: "interview, problem-solving, Fizz Buzz, hiring",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "forgetting-network",
    title: "Forgetting how your Legacy Network Works",
    image: "forgetting-network.jpg",
    headline: "The art of excuses",
    color: "lime",
    tags: "networks, devops, excuses",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "friend-gay-furries",
    title: "Being Friends with Gay Furries",
    image: "friend-gay-furries.jpg",
    headline: "Learn to Accept That the Other Engineers Are Dogs",
    color: "blue",
    tags: "friendship, acceptance, diversity",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "functional-thinking",
    title: "Functional Thinking",
    image: "functional-thinking.jpg",
    headline: "Paradigm over syntax",
    color: "fuchsia",
    tags: "functional programming, development, paradigm, syntax",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "getting-it-to-work",
    title: "Getting it to Work",
    image: "getting-it-to-work.jpg",
    headline: "Achievement despite ignorance",
    color: "blue",
    tags: "problem-solving, development, error, debugging",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "getting-lgtm-out-of-this-obstructionist",
    title: 'Getting "LGTM" Out of This Obstructionist Prick',
    image: "getting-lgtm-out-of-this-obstructionist.jpg",
    headline:
      "The Essential Guide to His Mental Code Linter & Outdated SQL Performance Tips",
    color: "yellow",
    tags: "code, review, collaboration, communication, senior, github",
    createdAt: "2024-02-04T13:00:00.000Z",
  },
  {
    id: "good-enough-to-ship",
    title: "Good Enough to Ship",
    image: "good-enough-to-ship.jpg",
    headline: "Letting your baby out of the nest - for better or worse",
    color: "red",
    tags: "product, devops, development, quality",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "google-error-message",
    title: "Googling the Error Message",
    image: "google-error-message.jpg",
    headline: "The internet will make those bad words go away",
    color: "blue",
    tags: "error, debugging, Google, stack overflow, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "googling-for-the-regex",
    title: "Googling for the Regex",
    image: "googling-for-the-regex.jpg",
    headline: "The Internet will do the remembering for you",
    color: "pink",
    tags: "regex, development, search, Google, stack overflow",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "guy-who-wrote-this-is-gone",
    title: "The Guy Who Wrote This Is Gone",
    image: "guy-who-wrote-this-is-gone.jpg",
    headline: "No comments, no documentation but 20 tickets",
    color: "teal",
    tags: "documentation, old, code, development, maintenance",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "hating-language",
    title: "Hating on Languages You Don't Use",
    image: "hating-language.jpeg",
    headline: "Your taste, experiences, and objectives are the absolute truth",
    color: "sky",
    tags: "team, opinions, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "hating-other-code",
    title: "Hating Other People's Code",
    image: "hating-other-code.jpg",
    headline: "It's only a clever hack if you're the one who wrote it",
    color: "teal",
    tags: "code, development, collaboration, github",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "hiring-ninjas",
    title: "Hiring Ninjas",
    image: "hiring-ninjas.jpg",
    headline: "Ninjas love open office layouts and unlimited vacation time",
    color: "blue",
    tags: "hiring, interview, LeetCode",
    createdAt: "2024-01-27T12:00:00.000Z",
  },
  {
    id: "holy-c",
    title: "Holy C",
    image: "holy-c.jpg",
    headline: "Divine Instructions | Gods software temple",
    color: "violet",
    tags: "cpp, development",
    createdAt: "2024-03-29T22:00:00.000Z",
  },
  {
    id: "hoping-nobody-hacks",
    title: "Hoping Nobody Hacks You",
    image: "hoping-nobody-hacks.jpg",
    headline: "Security by optimism and prayer",
    color: "sky",
    tags: "security, hacking, risk, user, client",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "hoping-right-interview",
    title: "Hoping for the Right Interview Questions",
    image: "hoping-right-interview.jpg",
    headline: "Banking on the 10% you know without Googling",
    color: "blue",
    tags: "interview, LeetCode, luck",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "hoping-this-works",
    title: "Hoping This Works",
    image: "hoping-this-works.jpg",
    headline: "Solutions that might fix the problem without breaking anything",
    color: "blue",
    tags: "problem-solving, development, broken",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "hype-driven-development",
    title: "Hype Driven Development",
    image: "hype-driven-development.jpg",
    headline:
      "Looking for love in all the wrong frameworks | Life on the Bandwagon",
    color: "violet",
    tags: "development, technology, trends, risk",
    createdAt: "2024-06-06T20:40:00.000Z",
  },
  {
    id: "ignoring-deprecation-warnings",
    title: "Ignoring Deprecation Warnings",
    image: "ignoring-deprecation-warnings.jpg",
    headline: "Maybe they'll just go away on their own.",
    color: "teal",
    tags: "error, development, dependencies, maintenance",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "imaginary-scaling-issues",
    title: "Solving Imaginary Scaling Issues",
    image: "imaginary-scaling-issues.jpg",
    headline:
      "At Scale | Getting the wrong idea from that conference talk you attended",
    color: "violet",
    tags: "scaling, performance, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "implementing-dumb-features",
    title: "Implementing Dumb Features",
    image: "implementing-dumb-features.jpg",
    headline: 'When nobody has the confidence to say "No"',
    color: "blue",
    tags: "features, management, development, communication, client",
    createdAt: "2024-01-27T14:00:00.000Z",
  },
  {
    id: "insulting-sha1-collisions",
    title: "Insulting SHA-1 Collisions",
    image: "insulting-sha1-collisions.jpg",
    headline: "Leave unmistakable traces in the project logs | git log",
    color: "lime",
    tags: "github, security, cryptography",
    createdAt: "2024-01-27T14:00:00.000Z",
  },
  {
    id: "it-depends",
    title: "It Depends",
    image: "it-depends.jpg",
    headline: "The answer to every programming question ever conceived",
    color: "teal",
    tags: "development, stack overflow, ambiguity, chatgpt",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "kubernetes-beginners",
    title: "Kubernetes for beginners",
    image: "kubernetes-beginners.jpg",
    headline: "Containers, that'll fix it. | What could go wrong?",
    color: "green",
    tags: "Kubernetes, containers, Docker, devops",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "learn-ml",
    title: "Learning Machine Learning",
    image: "learn-ml.png",
    headline: "Better buy 12 more GPUs",
    color: "violet",
    tags: "machine learning, chatgpt, GPU, education",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "lets-put-it-on-the-internet",
    title: "Let's Put It On The Internet",
    image: "lets-put-it-on-the-internet.jpg",
    headline:
      "Seriously, who's gonna find it? | A comprehensive guide to putting critical infrastructure online",
    color: "cyan",
    tags: "internet, security, devops, deployment",
    createdAt: "2024-03-29T22:00:00.000Z",
  },
  {
    id: "loosing-your-will-to-live",
    title: "Losing Your Will To Live",
    image: "loosing-your-will-to-live.jpg",
    headline:
      "Code Maintenance Guide | The original developer isn't here for a reason",
    color: "lime",
    tags: "code, maintenance, old, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "maintaining-open-source",
    title: "Thanklessly Maintaining Open Source Software",
    image: "maintaining-open-source.jpg",
    headline: "Acting out of the goodness of your heart, or something",
    color: "sky",
    tags: "open source, maintenance, GitHub",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "maintaining-status-quo",
    title: "Maintaining Status Quo",
    image: "maintaining-status-quo.jpg",
    headline: "When not doing just doesn't do",
    color: "red",
    tags: "development, management, excuses, code",
    createdAt: "2024-06-06T20:50:00.000Z",
  },
  {
    id: "making-a-slack-clone",
    title: "Making a Slack Clone",
    image: "making-a-slack-clone.jpg",
    headline: "Implementing their features on a shoestring budget",
    color: "cyan",
    tags: "management, development, startup, web",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "making-jeff-bezos-richer",
    title: "Making Jeff Bezos Richer",
    image: "making-jeff-bezos-richer.jpg",
    headline:
      "Why did I get charged $240 if I was just testing? | Depend utterly on AWS",
    color: "yellow",
    tags: "AWS, cloud, hosting, billing, devops",
    createdAt: "2024-01-27T14:00:00.000Z",
  },
  {
    id: "managing-ip-networks",
    title: "Managing IP Networks",
    image: "managing-ip-networks.jpg",
    headline: "with Cisco Router | Help for IP Network Administrators",
    color: "blue",
    tags: "networks, management, devops",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "managing-managers",
    title: "Managing Managers",
    image: "managing-managers.png",
    headline: "Dealing With Bad Managers | How To Fix What Your Manager Did",
    color: "blue",
    tags: "management, leadership, conflicts",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "mastering-the-go-type-system",
    title: "Mastering the Go type system",
    image: "mastering-the-go-type-system.jpg",
    headline:
      'Because "They are not capable of understanding a brilliant language". | if err != nil',
    color: "cyan",
    tags: "Go, type, development, nil",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "memorizing-six-git-commands",
    title: "Memorizing Six Git Commands",
    image: "memorizing-six-git-commands.jpg",
    headline: "The popular approach to version control",
    color: "teal",
    tags: "github, commands, complexity",
    createdAt: "2024-01-27T14:00:00.000Z",
  },
  {
    id: "microservices",
    title: "Microservices",
    image: "microservices.jpg",
    headline:
      "Protecting yourself against gratuitous network layers | Their Prevention and Cure",
    color: "violet",
    tags: "microservices, architecture, system, scalability",
    createdAt: "2024-01-27T14:00:00.000Z",
  },
  {
    id: "miss-meeting",
    title: "Excuses to Miss Meetings",
    image: "miss-meeting.jpg",
    headline: "Timing critical tasks to coincide with morning stand-up",
    color: "teal",
    tags: "meetings, time, management, excuses, productivity",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "moving-fast-and-breaking",
    title: "Moving Fast and Breaking Things",
    image: "moving-fast-and-breaking.jpg",
    headline: "Just put the technical debt on my credit card",
    color: "fuchsia",
    tags: "development, technology, agile, risk, broken",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "needless-dependencies",
    title: "Taking on Needless Dependencies",
    image: "needless-dependencies.jpeg",
    headline: "Code written by some stranger on the internet is always perfect",
    color: "red",
    tags: "dependencies, code, management, risk, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "no",
    title: "No",
    image: "no.jpeg",
    headline: "Literally the opposite of yes",
    color: "teal",
    tags: "fun, excuses, management",
    createdAt: "2024-07-06T11:00:00.000Z",
  },
  {
    id: "nodding-along",
    title: "Nodding Along",
    image: "nodding-along.jpeg",
    headline: "Pretending to understand concepts and acronyms",
    color: "red",
    tags: "development, trends, technology",
    createdAt: "2024-08-11T12:00:00.000Z",
  },
  {
    id: "not-writing-unit-tests",
    title: "Excuses for Not Writing Unit Tests",
    image: "not-writing-unit-tests.jpg",
    headline: "Your application is a special snowflake",
    color: "indigo",
    tags: "testing, excuses, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "one-million-tabs",
    title: "Managing + Navigating 1 Million Browser Tabs",
    image: "one-million-tabs.jpeg",
    headline: "Because you know you just saw the tab you need",
    color: "violet",
    tags: "management, development, productivity",
    createdAt: "2024-08-11T12:00:00.000Z",
  },
  {
    id: "overwriting-code",
    title: "Overwriting your teammates' code",
    image: "overwriting-code.png",
    headline: '"My code is better than yours anyway" | Be a team player',
    color: "teal",
    tags: "team, collaboration, code, review, development, github",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "own-parody-covers",
    title: "Making Your Own Parody Covers",
    image: "own-parody-covers.jpg",
    headline: "Dont even leave Slack to do it",
    color: "indigo",
    tags: "parody, creativity, design, fun",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "parsing-html-using-regex",
    title: "Parsing HTML using Regular Expressions",
    image: "parsing-html-using-regex.jpg",
    headline:
      "The ichor permeates MY FACE MY FACE oh god no NO NOO | No stop the angels are not real",
    color: "red",
    tags: "HTML, regex, parsing",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "pasting-code-from-2012-tutorial",
    title: "Pasting Code from Some Random 2012 Node.js Tutorial",
    image: "pasting-code-from-2012-tutorial.jpg",
    headline:
      "It was the first Google result and you only live once | And Hoping for the Best",
    color: "blue",
    tags: "google, Node.js, tutorial, copy-pasting, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "pedantic-arguments",
    title: "Winning Pedantic Arguments",
    image: "pedantic-arguments.jpg",
    headline:
      "Anyone who disagrees with you is your enemy and you must crush them",
    color: "fuchsia",
    tags: "arguments, communication, conflicts, team",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "phishing",
    title: "Phishing",
    image: "phishing.jpg",
    headline: "Professional Identity Theft Techniques",
    color: "cyan",
    tags: "phishing, cybersecurity, error, hacking",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "pointless-meeting",
    title: "Pointless Meetings",
    image: "pointless-meeting.jpg",
    headline: "How To Survive All The Pointless Meetings",
    color: "red",
    tags: "meetings, productivity, time, management, culture",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "practical-testing",
    title: "Practical Testing",
    image: "practical-testing.jpg",
    headline:
      "It worked fine three months ago | Just click around and see if anything breaks",
    color: "sky",
    tags: "testing, development, quality, debugging",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "pretending-to-know-about-stuff",
    title: "Pretending to Know About Stuff",
    image: "pretending-to-know-about-stuff.jpeg",
    headline: "Feigning knowledge of a word you've heard a few times",
    color: "teal",
    tags: "development, management, communication",
    createdAt: "2024-08-11T12:00:00.000Z",
  },
  {
    id: "pretending-you-know",
    title: "Pretending you know what you're doing",
    image: "pretending-you-know.jpeg",
    headline: "Advanced stack overflow copy pasting for beginners",
    color: "red",
    tags: "Stack Overflow, development, copy-pasting",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "printf-debugging",
    title: "printf() Debugging",
    image: "printf-debugging.jpg",
    headline: "Who needs breakpoints?",
    color: "teal",
    tags: "debugging, development, production",
    createdAt: "2024-01-27T13:00:00.000Z",
  },
  {
    id: "problem-that-dont-exist",
    title: "Solving Problems That Don't Exist",
    image: "problem-that-dont-exist.jpg",
    headline: "The Why's and How's",
    color: "red",
    tags: "problem-solving, development, complexity",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "procrastination",
    title: "Procrastination",
    image: "procrastination.png",
    headline: "The Why's and How's",
    color: "blue",
    tags: "procrastination, time, management, productivity",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "rationalizing-hackjob",
    title: "Rationalizing Your Awful Hackjob",
    image: "rationalizing-hackjob.jpg",
    headline:
      "Not thinking about how much pain this is going to cause in the future",
    color: "pink",
    tags: "rationalizing, hacking, development, problem-solving",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "redownloading-the-git-repo",
    title: "Redownloading the Git Repo",
    image: "redownloading-the-git-repo.jpg",
    headline: "Paste the changes | Ignoring Git Merge",
    color: "yellow",
    tags: "GitHub, merge, development, conflicts",
    createdAt: "2024-01-27T13:00:00.000Z",
  },
  {
    id: "regex-by-error",
    title: "Regex by Trial and Error",
    image: "regex-by-error.jpg",
    headline: "Combining slashes and dots until a thing happens",
    color: "blue",
    tags: "regex, error, debugging, development, pattern matching",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "remembering-what-to-google",
    title: "Remembering What to Google",
    image: "remembering-what-to-google.jpg",
    headline: "How you get anything done ever",
    color: "teal",
    tags: "Google, search, memory, productivity",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "resume-driven-dev",
    title: "Resume Driven Development",
    image: "resume-driven-dev.jpg",
    headline: "The passionate, functional, micro-serviced approach",
    color: "red",
    tags: "hiring, development, career, technology",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "rewriting-frontend",
    title: "Rewriting Your Front End Every Six Weeks",
    image: "rewriting-frontend.jpeg",
    headline:
      "This time you have definitely chosen the right libraries and build tools",
    color: "pink",
    tags: "frontend, development, refactoring, libraries, tools",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "rubber-duck-debugging",
    title: "Rubber Duck Debugging",
    image: "rubber-duck-debugging.jpg",
    headline: "Figuring it out without wasting someone elses time",
    color: "indigo",
    tags: "debugging, development, problem-solving, junior",
    createdAt: "2024-02-04T13:00:00.000Z",
  },
  {
    id: "rust-is-happy",
    title: "Adding and Removing & and * at random until rustc is happy",
    image: "rust-is-happy.png",
    headline: "50 essential concepts",
    color: "red",
    tags: "cpp, Rust, development, reference, pointer",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "saas-addiction",
    title: "SAAS Addiction",
    image: "saas-addiction.jpg",
    headline: "Maybe there's an API for that",
    color: "orange",
    tags: "aws, SAAS, addiction, cloud, software, API",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "saturday",
    title: "Saturday",
    image: "saturday.jpg",
    headline: "How to handle work saturation",
    color: "orange",
    tags: "work, life, burnout, productivity",
    createdAt: "2024-01-27T14:00:00.000Z",
  },
  {
    id: "scalable-parallel-computational-models",
    title: "Scalable parallel computational models",
    image: "scalable-parallel-computational-models.jpg",
    headline: "It works on my machine",
    color: "lime",
    tags: "parallel computing, scalability, system, cloud",
    createdAt: "2024-01-27T14:00:00.000Z",
  },
  {
    id: "schrodingers-backup",
    title: "Shrodinger's backup",
    image: "schrodingers-backup.jpg",
    headline:
      "The condition of any backup is unknown until a restore is attempted.",
    color: "fuchsia",
    tags: "backup, restore, data, risk, devops",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "security-next-month",
    title: "Getting Around to Security Next Month",
    image: "security-next-month.jpg",
    headline:
      "Putting off critical tasks until everyone forgets about them | If there's time",
    color: "teal",
    tags: "security, procrastination, risk, priorities",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "self-documenting-code",
    title: "Self-Documenting Code",
    image: "self-documenting-code.jpg",
    headline: "Who needs comments anyway?",
    color: "fuchsia",
    tags: "documentation, code, development, fun",
    createdAt: "2024-01-27T14:00:00.000Z",
  },
  {
    id: "server-down",
    title: "Loosing files",
    image: "server-down.png",
    headline: "book cover",
    color: "teal",
    tags: "loss, recovery, server, error, HTML",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "shitty-ddl-ref",
    title: "Restoring shitty .ddl references",
    image: "shitty-ddl-ref.jpg",
    headline: "Inheritance isn't always a good thing",
    color: "red",
    tags: "cpp, C++, inheritance, reference, code, oop",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "startup-success",
    title: "Startup Success",
    image: "startup-success.jpeg",
    headline: "TechCrunch Said This Was A Billion Dollar Market",
    color: "gray",
    tags: "startup, business, client, user",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "such-data",
    title: "Such Data",
    image: "such-data.jpg",
    headline: "So DevOps | Much Cloud | Very Agile",
    color: "blue",
    tags: "data, analytics, information, devops",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "surviving-the-kincade-fire",
    title: "Surviving the Kincade Fire",
    image: "surviving-the-kincade-fire.jpg",
    headline:
      "Or how not to put your servers in California | Our website melted",
    color: "red",
    tags: "recovery, risk, devops, server",
    createdAt: "2024-01-27T14:00:00.000Z",
  },
  {
    id: "talk-now-learn-later",
    title: "Talk Now Learn Later",
    image: "talk-now-learn-later.jpg",
    headline:
      "A guide to bluff at the project meetings to look smart | All-in-one book",
    color: "gray",
    tags: "communication, meetings, development, management",
    createdAt: "2024-03-29T22:00:00.000Z",
  },
  {
    id: "team-work-in-it",
    title: "Team Work in IT",
    image: "team-work-in-it.jpg",
    headline: "How to be productive despite it",
    color: "red",
    tags: "team, management, productivity, development",
    createdAt: "2024-06-06T20:55:00.000Z",
  },
  {
    id: "temporary-workarounds",
    title: "Temporary Workarounds",
    image: "temporary-workarounds.jpeg",
    headline: "Who are you kidding?",
    color: "teal",
    tags: "code, development, patterns, architecture",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "testing-in-production",
    title: "Testing In Production",
    image: "testing-in-production.jpg",
    headline: "Never worry about multiple environments again!",
    color: "green",
    tags: "guide, error, testing, production, development, environment",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "thankfulness",
    title: "Thankfulness",
    image: "thankfulness.jpeg",
    headline: "Recognizing how great we have it",
    color: "pink",
    tags: "success, team, production",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "the-cyber",
    title: "The Cyber",
    image: "the-cyber.jpg",
    headline: "Great cyber, the best cyber, yuuuuuge cyber",
    color: "cyan",
    tags: "cybersecurity, internet, technology, devops",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "the-importance-of-backing-up-data",
    title: "The Importance of Backing Up Data",
    image: "the-importance-of-backing-up-data.jpg",
    headline: "Oh god please copy | Copying from dying drives",
    color: "yellow",
    tags: "data, backup, loss, recovery, devops, copy-pasting",
    createdAt: "2024-01-27T13:00:00.000Z",
  },
  {
    id: "the-joys-of-generic-parameter-types",
    title: "The Joys of Generic Parameter Types",
    image: "the-joys-of-generic-parameter-types.jpg",
    headline:
      "Map<T, List<Map<? super Key, U>>> simpleMap | Java's Take on Abstraction",
    color: "green",
    tags: "Java, generics, abstraction, development, oop",
    createdAt: "2024-01-27T13:00:00.000Z",
  },
  {
    id: "three-space-indentation",
    title: "3 Space Indentation",
    image: "three-space-indentation.jpeg",
    headline: "Appreciating the best indentation style | The only true indent",
    color: "red",
    tags: "code, development, style",
    createdAt: "2024-08-11T12:00:00.000Z",
  },
  {
    id: "trivial-details",
    title: "Trivial Details",
    image: "trivial-details.jpeg",
    headline: "Perfecting the parts that don't matter",
    color: "sky",
    tags: "development, code, time",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "trying-stuff-until-it-works",
    title: "Trying Stuff Until it Works",
    image: "trying-stuff-until-it-works.jpg",
    headline: "Software can be chaotic, but we make it work",
    color: "violet",
    tags: "error, problem-solving, development, debugging",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "upsetting-with-python",
    title: "Upsetting Your Coworkers With Python",
    image: "upsetting-with-python.png",
    headline: "Using list, map, lambda, and filter on a single line",
    color: "fuchsia",
    tags: "Python, style, development, team",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "useless-git-commit-message",
    title: "Useless Git Commit Messages",
    image: "useless-git-commit-message.jpg",
    headline: 'git commit -m "changes"',
    color: "indigo",
    tags: "github, commit, collaboration",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "using-open-source-software",
    title: "Using Open Source Software",
    image: "using-open-source-software.jpg",
    headline: "That'll show 'em | Yelling at the maintainer",
    color: "red",
    tags: "open source, software, github, dependencies",
    createdAt: "2024-01-27T13:00:00.000Z",
  },
  {
    id: "vague-understanding-of-computer-science",
    title: "Vague Understanding Of Computer Science",
    image: "vague-understanding-of-computer-science.jpg",
    headline:
      "Probably be able explain a sorting algorithm if it ever comes up",
    color: "pink",
    tags: "science, algorithms, education",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "variable-naming",
    title: "Variable Naming",
    image: "variable-naming.png",
    headline: "The hardest part of coding | Shave Hours Off Any Project",
    color: "violet",
    tags: "naming, development, code, style",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "weekly-design-pivots",
    title: "Weekly Design Pivots",
    image: "weekly-design-pivots.jpg",
    headline: "Going in circles forever",
    color: "red",
    tags: "design, development, trends, management, architecture",
    createdAt: "2024-06-06T20:00:00.000Z",
  },
  {
    id: "what-is-ligma",
    title: "What is Ligma",
    image: "what-is-ligma.png",
    headline: "Prepare for the worst",
    color: "sky",
    tags: "Ligma, meme, internet, culture",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "whiteboard-algo",
    title: "Whiteboard Algorithms",
    image: "whiteboard-algo.jpeg",
    headline: "Useless skills for interviews at public tech companies.",
    color: "sky",
    tags: "old, algorithms, interview, technology, hiring",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "whiteboard-interviews",
    title: "Whiteboard Interviews",
    image: "whiteboard-interviews.png",
    headline:
      "Putting the candidate through the same bullshit you went through",
    color: "pink",
    tags: "interview, LeetCode, hiring",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "whole-app-in-head",
    title: "Keeping the Whole App in Your Head",
    image: "whole-app-in-head.jpg",
    headline: 'Also known as "job security"',
    color: "indigo",
    tags: "system, memory, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "windows-ram-forensics",
    title: "Windows RAM forensics",
    image: "windows-ram-forensics.jpg",
    headline: "Official guide | Navigating Task Manager",
    color: "green",
    tags: "Windows, RAM, task manager, troubleshooting",
    createdAt: "2024-01-27T13:00:00.000Z",
  },
  {
    id: "wont-fix-in-linter",
    title: "Using won't fix in your linter",
    image: "wont-fix-in-linter.png",
    headline: "How to improve your code quality",
    color: "blue",
    tags: "linter, quality, SonarQube, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "working-with-users",
    title: "Working with Users",
    image: "working-with-users.jpg",
    headline: "I didn't do anything! | You broke it! | I don't see ANYTHING",
    color: "sky",
    tags: "user, development, collaboration, communication, support, customer, client",
    createdAt: "2024-01-27T13:00:00.000Z",
  },
  {
    id: "works-on-my-pc",
    title: "Works on my machine",
    image: "works-on-my-pc.jpeg",
    headline: "How to convince your manager",
    color: "teal",
    tags: "development, debugging, environment, collaboration",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "writing-code-nobody-else-can-read",
    title: "Writing Code that Nobody Else Can Read",
    image: "writing-code-nobody-else-can-read.jpg",
    headline: "Does it run? Just leave it alone.",
    color: "violet",
    tags: "readability, collaboration, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "writing-documentation",
    title: "Writing documentation",
    image: "writing-documentation.png",
    headline: "ToDo | Coming soon",
    color: "red",
    tags: "documentation, task, development",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "z-index-1000",
    title: "Z-Index: 100000000000",
    image: "z-index-1000.jpg",
    headline: "Real World CSS | You've come this far, no going back now.",
    color: "sky",
    tags: "CSS, HTML, frontend, development, style",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "zoom-account",
    title: "ZOOM account, I have one!",
    image: "zoom-account.jpg",
    headline: "sharing my private information | who needs privacy",
    color: "red",
    tags: "privacy, meetings, communication",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "ack",
    title: "ACK",
    image: "ack.jpg",
    headline: "UNIX Power Tools",
    color: "teal",
    tags: "linux, tools, commands",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
  {
    id: "angry-admin",
    title: "Angry Admin",
    image: "angry-admin.jpg",
    headline: "Keeping Uppity Users At Bay | Find Your Inner Rage",
    color: "red",
    tags: "management, user, devops",
    createdAt: "2023-08-08T12:00:00.000Z",
  },
];

export default BOOK_LIBRARY;
