// TODO: add headlines
// TODO: add tags
// TODO: fix image quality
// TODO: optimize images
export const BOOKS_LIBRARY = [
  {
    title: "Getting an Arduino LED to Blink",
    image: "/book_covers/arduino-led-to-blink.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Blaming the User",
    image: "/book_covers/blaming-the-user.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Bloated JabbaScript Frameworks",
    image: "/book_covers/bloated-jabbascript.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Resolving Broken Dependencies",
    image: "/book_covers/broken-dependencies.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Building AI with HTML",
    image: "/book_covers/building-ai-with-html.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Changing Sfugg and Seeing What Happens",
    image: "/book_covers/changing-stuff-and-seeing.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Choosing Based on GitHub Stars",
    image: "/book_covers/choosing-based-on-github.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Coding Drunk",
    image: "/book_covers/coding-drunk.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Coding on the Weekend",
    image: "/book_covers/coding-on-weekend.jpg",
    headline:
      "a frustrating hobby | it's like weekday coding, but pants are optional",
    tags: "",
  },
  {
    title: "Turning Coffee Into Code",
    image: "/book_covers/coffee-into-code.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Collective Intelligence",
    image: "/book_covers/collective-intelligence.jpg",
    headline: "",
    tags: "",
  },
  {
    title:
      "Using Convoluted Coding Practices to Piece Together a Somehow Functional Product",
    image: "/book_covers/convoluted-coding-practices.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Copying and Pasting from Stack Overflow",
    image: "/book_covers/copying-and-pasting.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "My Code is Cross-Browser Compatible",
    image: "/book_covers/cross-browser-code.png",
    headline:
      "and other lies you tell yourself | designing large-scase web sites",
    tags: "",
  },
  {
    title: "Whatever Dan Abramov says to do",
    image: "/book_covers/dan-abramov-says.jpeg",
    headline: "Pure, functional, predictable, time travelling, handsome",
    tags: "",
  },
  {
    title: "Deleting Code",
    image: "/book_covers/deleting-code.jpg",
    headline: "Oh how good it feels",
    tags: "",
  },
  {
    title: "Demon Extraction",
    image: "/book_covers/demon-extraction.jpg",
    headline: "",
    tags: "daemon",
  },
  {
    title: "Destructive Git Commands",
    image: "/book_covers/destructive-git-commands.jpg",
    headline: "WTF just happened? | I hope you backed up your code",
    tags: "",
  },
  {
    title: "Drop Table",
    image: "/book_covers/drop-table.jpg",
    headline: "Now with user-generated content!",
    tags: "",
  },
  {
    title: "Excuses for Now Writing Documentation",
    image: "/book_covers/excuses-for-no-documentation.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Exiting Vim",
    image: "/book_covers/exiting-vim.jpg",
    headline:
      "Just memorize these fourteen contectually dependant instructions",
    tags: "impossible",
  },
  {
    title: "Exploiting Goodwill to advance your agenda",
    image: "/book_covers/exploiting-goodwill.png",
    headline: "why deny equal opportunity for all to contribute?",
    tags: "luck",
  },
  {
    title: "Throwing Faster Hardware At The Problem",
    image: "/book_covers/faster-hardware.jpg",
    headline:
      "Speeding up your software without needing to actually optimize your code",
    tags: "",
  },
  {
    title: "Being Friends with Gay Furries",
    image: "/book_covers/friend-gay-furries.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Functional Thinking",
    image: "/book_covers/functional-thinking.png",
    headline: "",
    tags: "",
  },
  {
    title: "Getting it to Work",
    image: "/book_covers/getting-it-to-work.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Googling the Error Message",
    image: "/book_covers/google-error-message.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Googling for the Regex",
    image: "/book_covers/googling-for-the-regex.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "The Guy Who Wrote This Is Gone",
    image: "/book_covers/guy-who-wrote-this-is-gone.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Hoping for the Right Interview Questions",
    image: "/book_covers/hoping-right-interview.jpg",
    headline: "Banking on the 10% you know without Googling",
    tags: "luck",
  },
  {
    title: "Hoping This Works",
    image: "/book_covers/hoping-this-works.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Ignoring Deprecation Warnings",
    image: "/book_covers/ignoring-deprecation-warnings.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Solving Imaginary Scaling Issues",
    image: "/book_covers/imaginary-scaling-issues.jpg",
    headline:
      "At Scale | Getting the wrong idea from that conference talk you attended",
    tags: "",
  },
  {
    title: "Interactivity",
    image: "/book_covers/interactivity.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "It Depends",
    image: "/book_covers/it-depends.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Losing Your Will To Live",
    image: "/book_covers/loosing-your-will-to-live.png",
    headline: "Code Maintenance Guide",
    tags: "",
  },
  {
    title: "Managing IP Networks",
    image: "/book_covers/managing-ip-networks.jpg",
    headline: "with Cisco Router | Help for IP Network Administrators",
    tags: "",
  },
  {
    title: "Excuses to Miss Meetings",
    image: "/book_covers/miss-meeting.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Excuses for Not Writing Unit Tests",
    image: "/book_covers/not-writing-unit-tests.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Making Your Own Parody Covers",
    image: "/book_covers/own-parody-covers.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Pasting Code from Some Random 2012 Node.js Tutorial",
    image: "/book_covers/pasting-code-from-2012-tutorial.jpg",
    headline: "",
    tags: "googling",
  },
  {
    title: "Pointless Meetings",
    image: "/book_covers/pointless-meeting.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Practical Testing",
    image: "/book_covers/practical-testing.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Solving Problems That Don't Exist",
    image: "/book_covers/problem-that-don't-exist.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Rationalizing Your Awful Hackjob",
    image: "/book_covers/rationalizing-hackjob.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Remembering What to Google",
    image: "/book_covers/remembering-what-to-google.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Resume Driven Development",
    image: "/book_covers/resume-driven-dev.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Getting Around to Security Next Month",
    image: "/book_covers/security-next-month.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Restoring shitty .ddl references",
    image: "/book_covers/shitty-ddl-ref.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Temporary Workarounds",
    image: "/book_covers/temporary-workarounds.jpeg",
    headline: "",
    tags: "",
  },
  {
    title: "Testing In Production",
    image: "/book_covers/testing-in-production.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Trying Stuff Until it Works",
    image: "/book_covers/trying-stuff-until-it-works.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Useless Git Commit Messages",
    image: "/book_covers/useless-git-commit-message.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Vague Understanding Of Computer Science",
    image: "/book_covers/vague-understanding-of-computer-science.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "What is Ligma",
    image: "/book_covers/what-is-ligma.png",
    headline: "",
    tags: "",
  },
  {
    title: "Whiteboard Interviews",
    image: "/book_covers/whiteboard-interviews.png",
    headline: "",
    tags: "",
  },
  {
    title: "Using won't fix in your linter",
    image: "/book_covers/wont-fix-in-linter.png",
    headline: "",
    tags: "",
  },
  {
    title: "Writing Code that Nobody Else Can Read",
    image: "/book_covers/writing-code-nobody-else-can-read.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Z-Index: 100000000000",
    image: "/book_covers/z-index-1000.jpg",
    headline: "Real World CSS",
    tags: "",
  },
  {
    title: "ZOOM account, I have one!",
    image: "/book_covers/zoom-account.jpg",
    headline: "sharing my private information | who needs privacy",
    tags: "",
  },
  { title: "ACK", image: "/book_covers/ack.jpg", headline: "", tags: "" },
  {
    title: "Angry Admin",
    image: "/book_covers/angry-admin.jpg",
    headline: "",
    tags: "",
  },
];
