// TODO: optimize images
export const BOOKS_LIBRARY = [
  {
    title: "10x Engineering",
    image: "/book_covers/10x-engineer.jpg",
    headline: "Money, fame, maintainable code",
    tags: "",
  },
  {
    title: "Agile Project Micromanagement",
    image: "/book_covers/agile-micromanagement.png",
    headline: 'Cognitive Dissonance as "Process" | Water-Fall with Stand-ups',
    tags: "",
  },
  {
    title: "Arbitrary Forecasts",
    image: "/book_covers/arbitrary-forecasts.jpg",
    headline: "Saying something so people feel better about giving you money",
    tags: "",
  },
  {
    title: "Getting an Arduino LED to Blink",
    image: "/book_covers/arduino-led-to-blink.jpg",
    headline:
      "Looks like it's back to pixels for you! | And Then Losing Interest",
    tags: "",
  },
  {
    title: "Avoid Using Dark Patterns",
    image: "/book_covers/avoid-using-dark-patterns.jpg",
    headline: "Do. Or do not. There is no try.",
    tags: "clean code",
  },
  {
    title: "Blaming the Architecture",
    image: "/book_covers/blaming-architecture.jpeg",
    headline: "Fundamentals of establishing a scapegoat",
    tags: "",
  },
  {
    title: "Blaming the User",
    image: "/book_covers/blaming-the-user.jpg",
    headline: "You're a 10x hacker and it must be someone else's fault.",
    tags: "",
  },
  {
    title: "Bloated JabbaScript Frameworks",
    image: "/book_covers/bloated-jabbascript.jpg",
    headline:
      "Han ma boo-kee, keelee ka-lya dooka. Wadja da boolya ra 1.9 Megabytes",
    tags: "",
  },
  {
    title: "Bracket Placement",
    image: "/book_covers/bracket-placement.png",
    headline: "From Friend To Enemy In Just One Day",
    tags: "",
  },
  {
    title: "Breaking the Back Button",
    image: "/book_covers/breaking-back-button.jpg",
    headline: "Ruining something the browser gave you for free",
    tags: "",
  },
  {
    title: "Resolving Broken Dependencies",
    image: "/book_covers/broken-dependencies.jpg",
    headline: '"What did I do to deserve this?"',
    tags: "",
  },
  {
    title: "Building AI with HTML",
    image: "/book_covers/building-ai-with-html.jpg",
    headline: "HyperText Machine Icarning",
    tags: "",
  },
  {
    title: "Buzzword-first Design",
    image: "/book_covers/buzzword-first-design.jpg",
    headline: "Fashion-forward development",
    tags: "",
  },
  {
    title: "Casual Sexism",
    image: "/book_covers/casual-sexism.jpg",
    headline:
      "Ensuring half the potential talent force feels uncomfortable and alienated",
    tags: "",
  },
  {
    title: "Changing Sfugg and Seeing What Happens",
    image: "/book_covers/changing-stuff-and-seeing.jpg",
    headline: "How to actually learn any new programming concept",
    tags: "",
  },
  {
    title: "Choosing Based on GitHub Stars",
    image: "/book_covers/choosing-based-on-github.jpg",
    headline: "Depending on a vague popularity contest",
    tags: "",
  },
  {
    title: "Useless Code Quality Metrics",
    image: "/book_covers/code-quality.jpeg",
    headline: "Blindly adhering to arbitrary standards",
    tags: "standard",
  },
  {
    title: "Coding Drunk",
    image: "/book_covers/coding-drunk.jpg",
    headline: "Thinking Outside The Bottle | Make Programming Fun Again",
    tags: "",
  },
  {
    title: "Coding on the Weekend",
    image: "/book_covers/coding-on-weekend.jpg",
    headline:
      "a frustrating hobby | it's like weekday coding, but pants are optional",
    tags: "",
  },
  {
    title: "Turning Coffee Into Code",
    image: "/book_covers/coffee-into-code.jpg",
    headline:
      "It would be a pure function if not for the side effects on your sanity",
    tags: "",
  },
  {
    title: "Collective Intelligence",
    image: "/book_covers/collective-intelligence.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Compile Again and Pray to Work",
    image: "/book_covers/compile-and-pray.jpeg",
    headline: "Because something may change",
    tags: "",
  },
  {
    title: "JPEG compression",
    image: "/book_covers/compression.jpeg",
    headline: "",
    tags: "",
  },
  {
    title:
      "Using Convoluted Coding Practices to Piece Together a Somehow Functional Product",
    image: "/book_covers/convoluted-coding-practices.jpg",
    headline:
      "Gain expertise using phrases similar to \"If it ain't broke, don t fix it",
    tags: "",
  },
  {
    title: "Cookie Consent and Other Ways to Obstruct the Web Page",
    image: "/book_covers/cookie-consent.png",
    headline: "Because the Web isn't unusable enough yet",
    tags: "",
  },
  {
    title: "Copying and Pasting from Stack Overflow",
    image: "/book_covers/copying-and-pasting.jpg",
    headline: "Cutting corners to meet arbitrary management deadlines",
    tags: "",
  },
  {
    title: "My Code is Cross-Browser Compatible",
    image: "/book_covers/cross-browser-code.png",
    headline:
      "and other lies you tell yourself | designing large-scase web sites",
    tags: "",
  },
  {
    title: "Whatever Dan Abramov says to do",
    image: "/book_covers/dan-abramov-says.jpeg",
    headline: "Pure, functional, predictable, time travelling, handsome",
    tags: "",
  },
  {
    title: "Deleting Code",
    image: "/book_covers/deleting-code.jpg",
    headline:
      "Oh how good it feels | Probably the most satisfying part of your job. Is that sad?",
    tags: "",
  },
  {
    title: "Demon Extraction",
    image: "/book_covers/demon-extraction.jpg",
    headline: "A Guide To Removing Unwanted Evil Spirits",
    tags: "daemon",
  },
  {
    title: "Destructive Git Commands",
    image: "/book_covers/destructive-git-commands.jpg",
    headline: "WTF just happened? | I hope you backed up your code",
    tags: "",
  },
  {
    title: "Developing in Production",
    image: "/book_covers/develop-in-prod.jpeg",
    headline: "The fastest time to market",
    tags: "",
  },
  {
    title: "Drop Table",
    image: "/book_covers/drop-table.jpg",
    headline: "Now with user-generated content!",
    tags: "",
  },
  {
    title: "Endless Boilerplate",
    image: "/book_covers/endless-boilerplate.jpg",
    headline: "Hello, ridiculously complicated world",
    tags: "",
  },
  {
    title: "Excuses for Now Writing Documentation",
    image: "/book_covers/excuses-for-no-documentation.jpg",
    headline:
      "Where's the fun in just knowing what the code is supposed to do?",
    tags: "",
  },
  {
    title: "Exiting Vim",
    image: "/book_covers/exiting-vim.jpg",
    headline:
      "Just memorize these fourteen contectually dependant instructions",
    tags: "impossible",
  },
  {
    title: "Exploiting Goodwill to advance your agenda",
    image: "/book_covers/exploiting-goodwill.png",
    headline: "why deny equal opportunity for all to contribute?",
    tags: "luck",
  },
  {
    title: "Throwing Faster Hardware At The Problem",
    image: "/book_covers/faster-hardware.jpg",
    headline:
      "Speeding up your software without needing to actually optimize your code",
    tags: "cpu gpu ram memory",
  },
  {
    title: "Fear of Missing Out",
    image: "/book_covers/fear-of-missing-out.jpg",
    headline:
      "If you're not running distributed Rust, Go, Elixir and Scala microservices with an elm front end, Apache Storm stream processing, and integrating with Facebook Messenger, Amazon Echo, and gathering machine learning data from my Samsung refrigerator, what are you even doing?",
    tags: "",
  },
  {
    title: "Fitting Actual User Data Into The Design",
    image: "/book_covers/fitting-actual-user-data.jpg",
    headline: "People have names of varying lengths, who knew?",
    tags: "",
  },
  {
    title: "Fizz Buzz",
    image: "/book_covers/fizz-buzz.jpeg",
    headline: "Ensuring the futility of your interview process",
    tags: "learn",
  },
  {
    title: "Forgetting how your Legacy Network Works",
    image: "/book_covers/forgetting-network.jpg",
    headline: "The art of excuses",
    tags: "",
  },
  {
    title: "Being Friends with Gay Furries",
    image: "/book_covers/friend-gay-furries.jpg",
    headline: "Learn to Accept That the Other Engineers Are Dogs",
    tags: "",
  },
  {
    title: "Functional Thinking",
    image: "/book_covers/functional-thinking.png",
    headline: "",
    tags: "",
  },
  {
    title: "Getting it to Work",
    image: "/book_covers/getting-it-to-work.jpg",
    headline: "Achievement despite ignorance",
    tags: "",
  },
  {
    title: "Good Enough to Ship",
    image: "/book_covers/good-enough-to-ship.jpg",
    headline: "Letting your baby out of the nest - for better or worse",
    tags: "",
  },
  {
    title: "Googling the Error Message",
    image: "/book_covers/google-error-message.jpg",
    headline: "The internet will make those bad words go away",
    tags: "",
  },
  {
    title: "Googling for the Regex",
    image: "/book_covers/googling-for-the-regex.jpg",
    headline: "The Internet will do the remembering for you",
    tags: "",
  },
  {
    title: "The Guy Who Wrote This Is Gone",
    image: "/book_covers/guy-who-wrote-this-is-gone.jpg",
    headline: "No comments, no documentation but 20 tickets",
    tags: "",
  },
  {
    title: "Hating on Languages You Don't Use",
    image: "/book_covers/hating-language.jpeg",
    headline: "Your taste, experiences, and objectives are the absolute truth",
    tags: "",
  },
  {
    title: "Hating Other People's Code",
    image: "/book_covers/hating-other-code.jpg",
    headline: "It's only a clever hack if you're the one who wrote it",
    tags: "",
  },
  {
    title: "Hoping Nobody Hacks You",
    image: "/book_covers/hoping-nobody-hacks.jpg",
    headline: "Security by optimism and prayer",
    tags: "",
  },
  {
    title: "Hoping for the Right Interview Questions",
    image: "/book_covers/hoping-right-interview.jpg",
    headline: "Banking on the 10% you know without Googling",
    tags: "luck",
  },
  {
    title: "Hoping This Works",
    image: "/book_covers/hoping-this-works.jpg",
    headline: "Solutions that might fix the problem without breaking anything",
    tags: "",
  },
  {
    title: "Ignoring Deprecation Warnings",
    image: "/book_covers/ignoring-deprecation-warnings.jpg",
    headline: "Maybe they'll just go away on their own.",
    tags: "",
  },
  {
    title: "Solving Imaginary Scaling Issues",
    image: "/book_covers/imaginary-scaling-issues.jpg",
    headline:
      "At Scale | Getting the wrong idea from that conference talk you attended",
    tags: "",
  },
  {
    title: "It Depends",
    image: "/book_covers/it-depends.jpg",
    headline: "The answer to every programming question ever conceived",
    tags: "",
  },
  {
    title: "Kubernetes for beginners",
    image: "/book_covers/kubernetes-beginners.jpg",
    headline: "Containers, that'll fix it. | What could go wrong?",
    tags: "docker",
  },
  {
    title: "Learning Machine Learning",
    image: "/book_covers/learn-ml.png",
    headline: "Better buy 12 more GPUs | ",
    tags: "",
  },
  {
    title: "Losing Your Will To Live",
    image: "/book_covers/loosing-your-will-to-live.png",
    headline:
      "Code Maintenance Guide | The original developer isn't here for a reason",
    tags: "",
  },
  {
    title: "Thanklessly Maintaining Open Source Software",
    image: "/book_covers/maintaining-open-source.jpg",
    headline: "Acting out of the goodness of your heart, or something",
    tags: "github",
  },
  {
    title: "Managing IP Networks",
    image: "/book_covers/managing-ip-networks.jpg",
    headline: "with Cisco Router | Help for IP Network Administrators",
    tags: "",
  },
  {
    title: "Managing Managers",
    image: "/book_covers/managing-managers.png",
    headline: "Dealing With Bad Managers | How To Fix What Your Manager Did",
    tags: "",
  },
  {
    title: "Excuses to Miss Meetings",
    image: "/book_covers/miss-meeting.jpg",
    headline: "Timing critical tasks to coincide with morning stand-up",
    tags: "",
  },
  {
    title: "Moving Fast and Breaking Things",
    image: "/book_covers/moving-fast-and-breaking.jpg",
    headline: "Just put the technical debt on my credit card",
    tags: "",
  },
  {
    title: "Taking on Needless Dependencies",
    image: "/book_covers/needless-dependencies.jpeg",
    headline: "Code written by some stranger on the internet is always perfect",
    tags: "",
  },
  {
    title: "Excuses for Not Writing Unit Tests",
    image: "/book_covers/not-writing-unit-tests.jpg",
    headline: "Your application is a special snowflake",
    tags: "",
  },
  {
    title: "Overwriting your teammates' code",
    image: "/book_covers/overwriting-code.png",
    headline: '"My code is better than yours anyway" | Be a team player',
    tags: "",
  },
  {
    title: "Making Your Own Parody Covers",
    image: "/book_covers/own-parody-covers.jpg",
    headline: "Dont even leave Slack to do it",
    tags: "",
  },
  {
    title: "Pasting Code from Some Random 2012 Node.js Tutorial",
    image: "/book_covers/pasting-code-from-2012-tutorial.jpg",
    headline:
      "It was the first Google result and you only live once | And Hoping for the Best",
    tags: "googling",
  },
  {
    title: "Winning Pedantic Arguments",
    image: "/book_covers/pedantic-arguments.jpg",
    headline:
      "Anyone who disagrees with you is your enemy and you must crush them",
    tags: "",
  },
  {
    title: "Phishing",
    image: "/book_covers/phishing.jpg",
    headline: "Professional Identity Theft Techniques",
    tags: "",
  },
  {
    title: "Pointless Meetings",
    image: "/book_covers/pointless-meeting.jpg",
    headline: "How To Survive All The Pointless Meetings",
    tags: "guide",
  },
  {
    title: "Practical Testing",
    image: "/book_covers/practical-testing.jpg",
    headline:
      "It worked fine three months ago | Just click around and see if anything breaks",
    tags: "",
  },
  {
    title: "Pretending you know what you're doing",
    image: "/book_covers/pretending-you-know.jpeg",
    headline: "Advanced stack overflow copy pasting for beginners",
    tags: "",
  },
  {
    title: "Solving Problems That Don't Exist",
    image: "/book_covers/problem-that-don't-exist.jpg",
    headline: "The Why's and How's",
    tags: "",
  },
  {
    title: "Procrastination",
    image: "/book_covers/procrastination.png",
    headline: "",
    tags: "lazy",
  },
  {
    title: "Rationalizing Your Awful Hackjob",
    image: "/book_covers/rationalizing-hackjob.jpg",
    headline:
      "Not thinking about how much pain this is going to cause in the future",
    tags: "",
  },
  {
    title: "Regex by Trial and Error",
    image: "/book_covers/regex-by-error.jpg",
    headline: "Combining slashes and dots until a thing happens",
    tags: "",
  },
  {
    title: "Remembering What to Google",
    image: "/book_covers/remembering-what-to-google.jpg",
    headline: "How you get anything done ever",
    tags: "",
  },
  {
    title: "Resume Driven Development",
    image: "/book_covers/resume-driven-dev.jpg",
    headline: "The passionate, functional, micro-serviced approach",
    tags: "",
  },
  {
    title: "Rewriting Your Front End Every Six Weeks",
    image: "/book_covers/rewriting-frontend.jpeg",
    headline:
      "This time you have definitely chosen the right libraries and build tools",
    tags: "",
  },
  {
    title: "Adding and Removing & and * at random until rustc is happy",
    image: "/book_covers/rust-is-happy.png",
    headline: "",
    tags: "reference pointer rust cpp",
  },
  {
    title: "SAAS Addiction",
    image: "/book_covers/saas-addiction.jpg",
    headline: "Maybe there's an API for that",
    tags: "aws cloud software",
  },
  {
    title: "Getting Around to Security Next Month",
    image: "/book_covers/security-next-month.jpg",
    headline:
      "Putting off critical tasks until everyone forgets about them | If there's time",
    tags: "procrastination",
  },
  {
    title: "Loosing files",
    image: "/book_covers/server-down.png",
    headline: "",
    tags: "image not found html error",
  },
  {
    title: "Restoring shitty .ddl references",
    image: "/book_covers/shitty-ddl-ref.jpg",
    headline: "Inheritance isn't always a good thing",
    tags: "cpp",
  },
  {
    title: "Startup Success",
    image: "/book_covers/startup-success.jpeg",
    headline: "TechCrunch Said This Was A Billion Dollar Market",
    tags: "",
  },
  {
    title: "Such Data",
    image: "/book_covers/such-data.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Temporary Workarounds",
    image: "/book_covers/temporary-workarounds.jpeg",
    headline: "",
    tags: "bad code",
  },
  {
    title: "Testing In Production",
    image: "/book_covers/testing-in-production.jpg",
    headline: "Never worry about multiple environments again!",
    tags: "guide error",
  },
  {
    title: "Thankfulness",
    image: "/book_covers/thankfulness.jpeg",
    headline: "Recognizing how great we have it",
    tags: "success win production",
  },
  {
    title: "Trivial Details",
    image: "/book_covers/trivial-details.jpeg",
    headline: "Perfecting the parts that don't matter",
    tags: "",
  },
  {
    title: "Trying Stuff Until it Works",
    image: "/book_covers/trying-stuff-until-it-works.jpg",
    headline: "Software can be chaotic, but we make it work",
    tags: "",
  },
  {
    title: "Upsetting Your Coworkers With Python",
    image: "/book_covers/upsetting-with-python.png",
    headline: "Using list, map, lambda, and filter on a single line",
    tags: "",
  },
  {
    title: "Useless Git Commit Messages",
    image: "/book_covers/useless-git-commit-message.jpg",
    headline: "",
    tags: "",
  },
  {
    title: "Vague Understanding Of Computer Science",
    image: "/book_covers/vague-understanding-of-computer-science.jpg",
    headline:
      "Probably be able explain a sorting algorithm if it ever comes up",
    tags: "",
  },
  {
    title: "Variable Naming",
    image: "/book_covers/variable-naming.png",
    headline: "The hardest part of coding | Shave Hours Off Any Project",
    tags: "",
  },
  {
    title: "What is Ligma",
    image: "/book_covers/what-is-ligma.png",
    headline: "Prepare for the worst",
    tags: "",
  },
  {
    title: "Whiteboard Algorithms",
    image: "/book_covers/whiteboard-algo.jpeg",
    headline: "Useless skills for interviews at public tech companies.",
    tags: "old",
  },
  {
    title: "Whiteboard Interviews",
    image: "/book_covers/whiteboard-interviews.png",
    headline:
      "Putting the candidate through the same bullshit you went through",
    tags: "leetcode",
  },
  {
    title: "Keeping the Whole App in Your Head",
    image: "/book_covers/whole-app-in-head.jpg",
    headline: 'Also known as "job security"',
    tags: "",
  },
  {
    title: "Using won't fix in your linter",
    image: "/book_covers/wont-fix-in-linter.png",
    headline: "How to improve your code quality",
    tags: "sonarqube",
  },
  {
    title: "Works on my machine",
    image: "/book_covers/works-on-my-pc.jpeg",
    headline: "How to convince your manager",
    tags: "",
  },
  {
    title: "Writing Code that Nobody Else Can Read",
    image: "/book_covers/writing-code-nobody-else-can-read.jpg",
    headline: "Does it run? Just leave it alone.",
    tags: "",
  },
  {
    title: "Writing documentation ",
    image: "/book_covers/writing-documentation.png",
    headline: "ToDo | Coming soon",
    tags: "to do",
  },
  {
    title: "Z-Index: 100000000000",
    image: "/book_covers/z-index-1000.jpg",
    headline: "Real World CSS | You've come this far, no going back now.",
    tags: "",
  },
  {
    title: "ZOOM account, I have one!",
    image: "/book_covers/zoom-account.jpg",
    headline: "sharing my private information | who needs privacy",
    tags: "",
  },
  {
    title: "ACK",
    image: "/book_covers/ack.jpg",
    headline: "UNIX Power Tools",
    tags: "",
  },
  {
    title: "Angry Admin",
    image: "/book_covers/angry-admin.jpg",
    headline: "Keeping Uppity Users At Bay | Find Your Inner Rage",
    tags: "",
  },
];
